export const projects = [
  {
    img: "https://ik.imagekit.io/rt3e1gwcw/Screenshot%202024-11-07%20at%209.50.webp",
    title: "Interactive and Optimized Landing Pages",
    des: "Led the design and development of multiple landing pages aimed at boosting user engagement and conversion rates. Focused on crafting visually appealing layouts and implementing responsive design for optimal performance around 70+ across devices.",
    demo: "",
    live: "https://leapscholar.com/ielts-optimized-pages/ielts-landing-page-11-native",
    gitHub: "",
    technologies: ["HTML", "CSS", "JavaScript", "Next.js", "Responsive Design"],
  },
  {
    img: "https://ik.imagekit.io/rt3e1gwcw/Screenshot%202024-11-07%20at%209.05.webp",
    title: "User Dashboard",
    des: "Spearheaded the development of a dynamic and comprehensive user dashboard. Collaborated with stakeholders to gather requirements, conducted user testing, and iterated on the design to enhance user satisfaction.",
    demo: "",
    live: "https://leapscholar.com/test-prep/dashboard/",
    gitHub: "",
    technologies: ["Next.js", "Redux", "JavaScript", "User Testing"],
  },
  {
    img: "https://ik.imagekit.io/rt3e1gwcw/Screenshot%202024-11-07%20at%209.07.webp",
    title: "Mock Test Platform for IELTS Preparation",
    des: "Developed a mock test platform tailored for IELTS preparation, featuring real-time scoring functionality. Designed responsive user interfaces to enhance accessibility and performance across devices.",
    demo: "",
    live: "",
    gitHub: "",
    technologies: ["Next.js", "Redux", "JavaScript", "Responsive Design"],
  },
  {
    img: "https://ik.imagekit.io/rt3e1gwcw/Screenshot%202024-11-07%20at%209.08.webp",
    title: "Chat-Based IELTS Evaluation System",
    des: "Built a chat-based evaluation system for IELTS assessment using GPT-3. Implemented interactive features like voice recognition and text analysis, conducting usability testing to improve accuracy and reliability.",
    demo: "",
    live: "",
    gitHub: "",
    technologies: [
      "GPT-3",
      "JavaScript",
      "Voice Recognition",
      "Text Analysis",
      "Usability Testing",
    ],
  },
  {
    img: "https://ik.imagekit.io/rt3e1gwcw/Screenshot%202024-11-07%20at%209.10.webp",
    title: "Data Entry Portal",
    des: "Created a user-friendly data entry portal to streamline data collection and management processes. Designed dynamic interfaces for efficient data entry and validation.",
    demo: "",
    live: "",
    gitHub: "",
    technologies: ["Next.js", "JavaScript", "Data Validation"],
  },
];
